### ISSUE TITLE
error unity with example provided

### ISSUE THREAD

**Issue by eonianvr** [wit-ai/wit-unity#20]
I created the created wit configuration file and called it from the SHAPE example inside the wit(script).

I get an error "**Configuration is not set. Cannot start request.**" when running the Shape unity example.

![image](https://user-images.githubusercontent.com/44927690/127248573-ca02c2a5-56d4-4368-8f58-ddc61cf1707e.png)

**Comment by yolanother** [comment]
Make sure your Wit object in your scene has its wit configuration value set. That's where the scene gets it at runtime.

![image](https://user-images.githubusercontent.com/645359/127373437-a5ab23c9-bf55-4ac0-8874-ab5a272ec528.png)

**Comment by eonianvr** [comment]
Hi, 
I did that indeed. The error is still showing (unity 2019.4.8f1)

**Comment by eonianvr** [comment]
problem solved. I was just plain stupid and accidentally grab the demo scene from the package instead of the assets.
