### ISSUE TITLE
Wit.ai import fails with 'The type or namespace name 'WitConfiguration' could not be found'

### ISSUE THREAD

**Issue by baroquedub** [wit-ai/wit-unity#59]
Was able to install Wit.ai from the package manager (Add package from git URL) without any problems a few days ago.

Today I'm getting spammed with `The type or namespace name 'WitConfiguration' could not be found`
![image](https://user-images.githubusercontent.com/316458/140135366-87c5b9b5-79ec-4d8e-b63d-88a29e875923.png)

Brand new Unity 2020.3.17f1 project. Nothing else imported.

**Comment by CWolfe1320** [comment]
Seconded issue- my team is experiencing this as well.

**Comment by chessai** [comment]
@yolanother Is this related to recent changes?

**Comment by yolanother** [comment]
This is an issue with our build system internally in preperation for voice-sdk. I'll get a fixed branch up asap while we figure out what happened to the build system.

**Comment by yolanother** [comment]
Here is a branch with a test of v0.0.20 and the repaired directory structure. This should get you unblocked while I figure out what happened with the build system.

https://github.com/wit-ai/wit-unity/tree/repaired-dir-structure

**Comment by yolanother** [comment]
This should now be fixed on main as well. The branch should no longer be necessary.
