### ISSUE TITLE
Abort being called after each voice recording

### ISSUE THREAD

**Issue by CWolfe1320** [wit-ai/wit-unity#60]
![Debug Log](https://user-images.githubusercontent.com/68285085/140663317-164b1dc6-c072-4476-a9f8-e3dcf09b1a39.png)
Test branch is aborting any Wit interaction after listening for voice input. Sometimes audio makes it through and appears on the wit.ai project (maybe like a 30% chance), but we never receive a WitResponseNode. Testing the Wit object with written utterances works, and generates the WitResponseNode. Me and my team have been trying to trouble shoot this all day, but have no idea if this is an us issue, or an unstable branch issue. Any guidance one way or another would be greatly appreciated.

**Comment by yolanother** [comment]
@CWolfe1320 yeah sorry about the issue. This branch is somewhat unstable. If your team needs stability I'd recommend using one of the releases. Your issue above should be resolved in my latest push to this branch. This branch was based on a recent change that introduced some instability in main and I've been slowly working through a series of fallout bugs and improvements. These are pretty highly experimental and haven't been through any QA process yet. I'm hoping to have all of this pushed back to main and through QA sometime this week. In general master is more unstable than the numbered releases available through the release channel: https://github.com/wit-ai/wit-unity/releases. New changes go into master for testing and once we're satisfied they are stable we create a tag and push them to the releases channel.

**Comment by yolanother** [comment]
I just updated the branch with the latest changes and fixes from code review feedback. It should be reasonably stable at this point and will be merged into master. We may still be having build issues with integrations into master. We are still looking into that issue. These changes still haven't hit QA yet. When they have gone through QA signoff they will get pushed to v0.0.20 in the release channel.

**Comment by yolanother** [comment]
This should now be fixed.
