### ISSUE TITLE
NullReferenceException when starting recording if there are no connected microphones

### ISSUE THREAD

**Issue by jesperlundqvist** [wit-ai/wit-unity#64]
We've discovered a bug when starting recording on a device with no connected microphones. When starting the recording with Wit.Activate(), we get a NullReferenceException. See the stack trace below for details.

```
NullReferenceException: Object reference not set to an instance of an object
Facebook.WitAi.Lib.Mic.StartRecording (System.Int32 sampleLen) (at Assets/Oculus/Voice/Lib/Wit.ai/Scripts/Runtime/Lib/Mic.cs:229)
Facebook.WitAi.Wit.Activate (Facebook.WitAi.Configuration.WitRequestOptions requestOptions) (at Assets/Oculus/Voice/Lib/Wit.ai/Scripts/Runtime/Wit.cs:334)
Facebook.WitAi.Wit.Activate () (at Assets/Oculus/Voice/Lib/Wit.ai/Scripts/Runtime/Wit.cs:305)
```

Note that this is using the [Oculus Voice SDK](https://developer.oculus.com/experimental/voice-sdk-overview/).

This can be easily reproduced on Windows by disabling every sound input device in the sound settings.

**Comment by ramh** [comment]
Thank you so much for reporting the issue. We will take a look at this soon.

**Comment by yolanother** [comment]
@jesperlundqvist a fix for this has been checked in and is accessible via Wit-Unity v0.0.24. It will likely land in v37 of the Voice SDK.
