### ISSUE TITLE
Wit Configuration Window Inaccessible

### ISSUE THREAD

**Issue by DataIsGone** [wit-ai/wit-unity#65]
Hello, my project team is using Wit.AI for our school project for graduation.

At the beginning of this week one of us followed the Shapes tutorial and made the scene from scratch. They were able to access the Wit Configuration menu.
![image](https://user-images.githubusercontent.com/50283648/149564500-27e7ea90-1ceb-4cea-81e7-c3180c11d7f3.png)

The evening of Thursday, 01/13, another of our team members also went through the tutorial and can't see the Wit Configuration menu.
![image](https://user-images.githubusercontent.com/50283648/149565248-2e11caef-5309-46ad-9cb6-db612dd784fe.png)

We're wondering if this is an issue caused by commit 11a104c4d221ecb8e895d0bbac41a80def3e9878 where changes were made to the config window scripts. Will there be a fix soon?

**Comment by DataIsGone** [comment]
I remembered that I had forked this repo before the window changes occurred, so my team is okay for now.

Incase anyone else is trying to find a quick solution, you can get the previous version here:
https://github.com/DataIsGone/wit-unity

**Comment by wangpingsx** [comment]
I am also facing this issue. I found a workaround, hope it can help you as well:
1. Download the repo, unzip it and add it into your Assets folder.
2. Open yourProject/Assets/wit-unity-main/github/Scripts/Editor/WitEditorMenu.cs
3. Add `using Facebook.WitAi.CallbackHandlers;` under line 16
4. Save the change and back to Unity, then you should be able to see the menu.

**Comment by yolanother** [comment]
This should now be fixed.
