### ISSUE TITLE
Aborted with Error: Error - 7

### ISSUE THREAD

**Issue by mubeenfAhd** [wit-ai/wit-unity#71]
Everything worked perfectly on unity Editor but when I created an Android build for testing on my phone. When I clicked Activate button it shows "Microphone Listening.." but no JSON output is generated, instead I get this:
Error: Error - 7
Request timed out.
Scene: ResponseDebugger
Unity: 2019.4.10
I tried your latest version you updated 25 Mar 2022 but the same thing happened, so I downgraded it to 0.0.26 version.

Kindly help, I've attached a log file, maybe it will be of any help.

[logcat.log](https://github.com/wit-ai/wit-unity/files/8354735/logcat.log)
.

**Comment by yolanother** [comment]
Has it worked on any version with the mobile device you are testing on? We recently discovered a bug on phones that is preventing requests from executing and are looking into it.

**Comment by yolanother** [comment]
I see an auto rotation in your log. Did you rotate your phone while a request was active?

**Comment by yolanother** [comment]
We believe we have finally tracked this down. On Android you need to do two things. Make sure requires internet access is checked. Second you must use IL2CPP build. For some reason the request just fails on many versions of Unity in mono mode.
