### ISSUE TITLE
Response Matcher menu items are hidden

### ISSUE THREAD

**Issue by OnlineTeachingNow** [wit-ai/wit-unity#75]
In Unity version 2021.3.3f1, the first item in a list is hidden behind the second when expanded. This prevents the ability to add a formatted value event entirely, as the options can't be accessed. Screenshot attached. 

![image](https://user-images.githubusercontent.com/79048476/169662109-df05b8e9-1812-4385-8581-c0c6bbc57637.png)

**Comment by yolanother** [comment]
Sorry it took a while to spot this. We'll get someone to take a look at it.

**Comment by yolanother** [comment]
We did some digging and this is a known Unity Issue with 2021.3.3. I think it should be fixed in the next 2021.3.x release or two.
