### ISSUE TITLE
The type or namespace name 'WitTrait' could not be found (are you missing a using directive or an assembly reference?) on installing Wit.AI plugin for Unity using the GitHub URL

### ISSUE THREAD

**Issue by jigyasaagarwal** [wit-ai/wit-unity#78]
On installing Wit.AI for Unity using the github URL https://github.com/wit-ai/wit-unity.git I am getting the following errors:
Library\PackageCache\com.facebook.witai@22e6392146\Scripts\Editor\WitEditorMenu.cs(16,27): error CS0234: The type or namespace name 'Traits' does not exist in the namespace 'Facebook.WitAi.Data' (are you missing an assembly reference?)
Library\PackageCache\com.facebook.witai@22e6392146\Scripts\Editor\WitEditorMenu.cs(83,38): error CS0246: The type or namespace name 'WitApplication' could not be found (are you missing a using directive or an assembly reference?)
Library\PackageCache\com.facebook.witai@22e6392146\Scripts\Editor\WitEditorMenu.cs(88,38): error CS0246: The type or namespace name 'WitIntent' could not be found (are you missing a using directive or an assembly reference?)
Library\PackageCache\com.facebook.witai@22e6392146\Scripts\Editor\WitEditorMenu.cs(93,38): error CS0246: The type or namespace name 'WitEntity' could not be found (are you missing a using directive or an assembly reference?)
Library\PackageCache\com.facebook.witai@22e6392146\Scripts\Editor\WitEditorMenu.cs(98,38): error CS0246: The type or namespace name 'WitTrait' could not be found (are you missing a using directive or an assembly reference?)

I was able to install the plugin without any errors yesterday. Today, because of some other issue I was facing, I tried to remove and reinstall the plugin, and am getting these errors. I tried installing the plugin on another device which had Unity, but I'm getting the same error.

**Comment by yolanother** [comment]
@jigyasaagarwal if you are using Wit-Unity and not Voice SDK you probably need to do a rebase. We're in the process of updating namespaces in Wit Unity so you will likely see breakages for a week or so if you aren't using one of the release channels. If you aren't doing active development in Wit, I would recommend using one of the release packages or better yet Voice SDK from the Oculus Integration or developer download. They will be more stable for you. The main branch in Wit can be unstable.

**Comment by jigyasaagarwal** [comment]
Thanks @yolanother I was trying to install the Unity package from the git url, as mentioned in the documentation, that is why I was getting the current SDK version which is under development. I went to the releases page and installed one of the ZIP files of an earlier released LTS version and added it to my project, and it's working fine now.
